### ISSUE TITLE
Support Maven 3.2 

### ISSUE THREAD

**Issue by saardemri** [whitesource/maven-plugin#7]
The plugin failed while running under maven 3.2 (3.0+) the execution failed due to : 

java.lang.NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystemSession;

**Comment by itaimarko** [comment]
This was caused by maven breaking some APIs in version 3.1.x (see [here](https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound).)

Try using the latest version of the WhiteSource maven plugin. It is compatible with maven version 3.0.x, 3.1.x and 3.2.x.
